### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#1]
- [x] Fix CL Bin path support (the bin files it creates can have illegal file names) **Fixed:** see https://github.com/DeadSix27/waifu2x-converter-cpp/commit/f963753227a09749291e93bd6769446ba1bb3945
- [x] Fix Unicode support (Hard to fix on windows.. need help for that. (See unicode-testing branch))
- [ ] Fix test not using right model
- [ ] Fix crash when no image extension is supplied (Add auto detection?, or error out?)

Ill update this as I progress.

**Comment by max20091** [comment]
CL Bin path not found on Windows caused by latest AMD APP SDK 3.0 unlike version 2.9
To fix that, you need to add system variable entry
Variable entry: AMDAPPSDKROOT
Variable entry:  C:\Program Files (x86)\AMD APP SDK\3.0\ (or C:\Program Files\AMD APP SDK\3.0\ if your system is 32-bit)

**Comment by DeadSix27** [comment]
Any idea how to solve: 
```
7>w2xcr.obj : error LNK2019: unresolved external symbol __imp_w2xconv_convert_file referenced in function proc_thread
7>G:\waifu2x\waifu2x-converter-cpp\_output\Debug\w2xcr.exe : fatal error LNK1120: 1 unresolved externals
```
For some reason it throws this error now, I had it compiling just fine a second ago and changed nothing..

**Comment by max20091** [comment]
just skip compiling w2xcr, I didn't install VS2014 yet cuz I just reinstalled Windows :(

**Comment by DeadSix27** [comment]
w2xcr is the main compiler binary, isnt it? It links to the dll and creates the actual CLI interface..
OH and the CL bin path, i do not mean AMD openCL i mean the binary files it creates, i patched that a while ago, it creates illegal file names.. Ill tell you what i mean later, once i push the patch..

**Comment by DeadSix27** [comment]
Oh additional info:
Looking for C++ include opencv2/opencv.hpp - not found
thats why it does not compile the main CLI.
Not sure yet how to fix that.

**Comment by DeadSix27** [comment]
I added a proper building guide: [BUILDING.md](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md)

I also added a new release see: [waifu2x-converter-cpp 3.0 (OpenCV32,VC14)](https://github.com/DeadSix27/waifu2x-converter-cpp/releases)

Works fine now.

**Comment by DeadSix27** [comment]
@max20091 I invited you to Gitter, you can also head on my Discord if you'd like: https://discord.gg/2yBtrFT

**Comment by iame6162013** [comment]
>  Fix Unicode support (Hard to fix on windows.. need help for that. (See unicode-testing branch))

Do you mean that it's broken on all platforms and is especially hard to fix on windows or that only windows has this issue.
Just checked and didn't get an error when using a unicode character under linux.

**Comment by max20091** [comment]
It's Windows specific issue as Windows CMD doesn't support unicode by default, you will have to change system locale to fix this :(

**Comment by iame6162013** [comment]
Well, I didn't expect that, and it doesn't really sound like a waifu2x issue to me.

**Comment by DeadSix27** [comment]
@max20091 You have to use windows specific unicode functions and stuff, there is a way but I'm not that experienced in c(++)

**Comment by iame6162013** [comment]
Do you know where the program crashes/causes issues? 
Is this `W2XCONV_ERROR_IMWRITE_FAILED` the error?

**Comment by DeadSix27** [comment]
@iame6162013 yes

**Comment by iame6162013** [comment]
My pr should fix that specific issue.

**Comment by iame6162013** [comment]
Do note that i haven't tried it because I was getting build errors with vs2017 community.

**Comment by DeadSix27** [comment]
@iame6162013 Ye, I'll test it myself later.

**Comment by iame6162013** [comment]
@DeadSix27 I think it will still fail when running `image_src = cv::imread(..);`

**Comment by DeadSix27** [comment]
Closed in favor of separate issues.
